version: '3.3'
services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./api
        target: /app

  api-graphql:
    build:
      context: ./api-graphql
    ports:
      - "3500:3500"
    volumes:
      - type: bind
        source: ./api-graphql
        target: /app


  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./frontend
        target: /app