version: '3.3'
services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: ./api
        target: /app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./frontend
        target: /app